package lyricextractor;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;

import org.apache.pdfbox.pdmodel.PDDocument; 
import org.apache.pdfbox.text.PDFTextStripper; 
 
import java.io.File; 
import java.io.IOException; 
import java.io.PrintWriter;

import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author burg3
 */
public class LyricExtractor extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public LyricExtractor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Select PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Extract Lyrics");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jButton2)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Select bottle PDF to extract:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        
        
                
        
                String userDir = System.getProperty("user.home");
		JFileChooser j = new JFileChooser(userDir + "/Desktop/Songs");
                FileNameExtensionFilter filter;
                filter = new FileNameExtensionFilter(null, ".pdf");
                jfc.setFileFilter(filter);
                j.showOpenDialog(null);
                
                jTextField1.setText(j.getSelectedFile().toString());
                
                
                
                
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Extract Lyrics to text file:
        
      
        
      try {
          
            //Loading an existing document
            File file = new File(jTextField1.getText());
      
      
             //Instantiate PDFTextStripper class
             PDFTextStripper pdfStripper = null;
            
            PDDocument document = PDDocument.load(file);
            
            pdfStripper = new PDFTextStripper();
            
             //Retrieving text from PDF document
            String text = pdfStripper.getText(document);
            
            String[] lineArray = text.split(System.getProperty("line.separator"));
            
            String userDir = System.getProperty("user.home");
            String path = new String(userDir + "/Desktop/Songs/");
            String newName = file.getName().replace(".pdf", "");
            PrintWriter out = new PrintWriter(path + newName + ".txt");
            
            
            
                
            
            for(int i=2; i<lineArray.length; i++){
                if(lineArray[i].contains("LLC")){
                    lineArray[i] = "";
                }else if(lineArray[i].contains("©")){
                    lineArray[i] = "";
                }else if(lineArray[i].contains("(Bridge)")){
                    lineArray[i] = System.getProperty("line.separator") + "Bridge";
                }else if(lineArray[i].contains("(Ending)")){
                    lineArray[i] = System.getProperty("line.separator") + "Ending";
                }else if(lineArray[i].contains("(Pre-Chorus)")){
                    lineArray[i] = System.getProperty("line.separator") + "Pre-Chorus";
                }else if(lineArray[i].contains("(TAG)")){
                    lineArray[i] = System.getProperty("line.separator") + "TAG";
                }else if(lineArray[i].contains("(Interlude)")){
                    lineArray[i] = "Interlude";
                }else if(lineArray[i].startsWith("1")){
                    lineArray[i] = "";
                }else if(lineArray[i].contains("Verse 1")){
                    lineArray[i] = System.getProperty("line.separator") + "Verse 1";
                }else if(lineArray[i].contains("Verse 2")){
                    lineArray[i] = System.getProperty("line.separator") + "Verse 2";
                }else if(lineArray[i].contains("Verse 3")){
                    lineArray[i] = System.getProperty("line.separator") + "Verse 3";
                }else if(lineArray[i].contains("Chorus 1")){
                    lineArray[i] = System.getProperty("line.separator") + "Chorus 1";
                }else if(lineArray[i].contains("Chorus 2")){
                    lineArray[i] = System.getProperty("line.separator") + "Chorus 2";
                }else if(lineArray[i].contains("Misc")){
                    lineArray[i] = "";
                }
                out.println(lineArray[i]);
            }
            out.close();
            //Closing the document
             document.close();
             
              JOptionPane.showMessageDialog(null, "Success!");
      } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
      
      
      

     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LyricExtractor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LyricExtractor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LyricExtractor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LyricExtractor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LyricExtractor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
